elearning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from learn import urls
from . import settings
from django.conf.urls.static import static
from learn.views import search, About

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name = 'index'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('course/',include('learn.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('search', search, name = 'searchposts'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings. MEDIA_ROOT)

learn/urls.py
from django.urls import path
from learn.views import CourseListView, CourseDetailView, UserCreateView, login, logout_view, address, CartListView, payment, ContactListView, CategoryView, CategoryList
app_name ='learn'

urlpatterns =[
    path('',CourseListView.as_view(), name ='courselist'),
    path('<slug:slug>',CourseDetailView.as_view()),
    path('signup/', UserCreateView.as_view(), name ='signup'),
    path('login/', login, name ='login'),
    path('logout/', logout_view, name ='logout'),
    path('address/', address, name='address'),
    path('cart/', CartListView.as_view(), name = 'cartlist'),
    path('payment/', payment, name='payment'),
    path('contact/', ContactListView.as_view(), name='contact'),
    path('curriculum/',CategoryView.as_view(), name = 'curriculum'),
    path('curriculum/<url>', CategoryList.as_view()),
    ]
    

templates/about.html
{% extends 'base.html' %}
{% block title %} | About {% endblock %}

{% block bodyblock %}

<section class="text-gray-400 bg-blue-900 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex items-center lg:w-3/5 mx-auto border-b pb-10 mb-10 border-gray-800 sm:flex-row flex-col">
  
      <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
        <h2 class="text-white text-lg title-font font-medium mb-2">About</h2>
        <p class="leading-relaxed text-base">As we are already residing in the 21st Century, there wants to be changed in our way of living, and improvement starts from mastering so this platform would mechanically contribute toward human development via the field of education.
          Electronic gaining knowledge of the platform is a built-in set of interactive online choices that supply teachers, learners, dad, and mom, etc. concerned in education with information, tools, and assets to help and decorate instructional transport and management.
          </p>
      </div>
    </div>
    <div class="flex items-center lg:w-3/5 mx-auto border-b pb-10 mb-10 border-gray-800 sm:flex-row flex-col">
      <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
        <h2 class="text-white text-lg title-font font-medium mb-2">Features</h2>
        <p class="leading-relaxed text-base"> 	Students would easy find their desired courses with full learning means and mediums.
          Students would be able to learn on their desired time when evener they are free and intend to learn.
          Students would be able to learn from their own location, sitting on their couch at own rooms make them catch stuffs easily.
          Students would be able to learn at their own pace not by their school, colleges, and universities time limitations. 
          Payment of the desired course only need to be done by the learners.
          Reference their courses and find every resource in one location only.
          Payment method are also easy as the system itself contains one of the major payment methods integrated into it.
          Students also can select other courses rather from their desired course and keep on the Carts for future learning.
          Also, can contact the authorities for other important stuffs required for their learning.
       </p>
      </div>

    </div>
    <div class="flex items-center lg:w-3/5 mx-auto sm:flex-row flex-col">
      
      <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
        <h2 class="text-white text-lg title-font font-medium mb-2">Future Plan</h2>
        <p class="leading-relaxed text-base"> 	Develop this system with courses downloading feature.
          Develop the system with each course desired by the client.
          Integrating other various payment methods.
          Language selection system would be added in future so that not only the people who speaks English but also can read the site won their own native language or their mother tongue.
          Providing user with video tutorials in they system by changing the other flexible database system.
          Creating admin with better dashboard in future from where course information would be added properly.
          Implementing chatbot’s also would help user a lot. So, this feature also would be added in future.
       </p>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/base.html
<html>
<head>
    <title>{% block title %} {% endblock %} | E-learning</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    {% block head_section %}{% endblock %}
</head>
<body>

    <header class="text-gray-400 bg-pink-800 body-font">
        <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
            <a class="flex title-font font-medium items-center text-white mb-4 md:mb-0">
                <img src="https://s3.amazonaws.com/designmantic-logos/logos/2021/Mar/small-5145-605b76628a895.png">
                <span class="ml-3 text-xl">पाठशाला</span>
            </a>
            {% if user.is_authenticated %}
            <nav class="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center">
                <a class="mr-8 hover:text-white" href="{% url 'index' %}">E-Learning</a>
                <a class="mr-8 hover:text-white" href="{% url 'learn:courselist' %}">Courses</a>
                <a class="mr-8 hover:text-white" href="{% url 'learn:contact' %}">Contact</a>
                <a class="mr-8 hover:text-white" href="{% url 'learn:curriculum' %}">Curriculum</a>
                <a class="mr-8 hover:text-white" href="{% url 'about' %}">About</a>
                <a class="mr-8 hover:text-white" href="{% url 'learn:cartlist' %}">Cart</a>
            </nav>
            {% else %}
            <nav class="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center">
                <a class="mr-8 hover:text-white" href="{% url 'index' %}">E-Learning</a>
                <a class="mr-8 hover:text-white" href="{% url 'learn:courselist' %}">Courses</a>
                <a class="mr-8 hover:text-white" href="{% url 'learn:contact' %}">Contact</a>
                <a class="mr-8 hover:text-white" href="{% url 'about' %}">About</a>
            </nav>
            {% endif %}

            {% if user.is_authenticated %}
            <a href="{% url 'learn:logout' %}">
                <button class="inline-flex items-center bg-gray-800 border-0 py-1 px-3 focus:outline-none hover:bg-gray-700 rounded text-base mt-4 md:mt-0">
                    Logout
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                </button>
            </a>
            {% else %}
            <a href="{% url 'learn:signup' %}">
                <button class="inline-flex items-center bg-gray-800 border-0 py-1 px-3 focus:outline-none hover:bg-gray-700 rounded text-base mt-4 md:mt-0">
                    Signup
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                </button>&nbsp;
            </a>
            <a href="{% url 'learn:login' %}">
                <button class="inline-flex items-center bg-gray-800 border-0 py-1 px-3 focus:outline-none hover:bg-gray-700 rounded text-base mt-4 md:mt-0">
                    Login
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                </button>
            </a>
            {% endif %}
        </div>
    </header>
    {% block bodyblock %}
    {% endblock %}
    <footer class="text-gray-400 bg-pink-800 body-font">
        <div class="container px-5 py-4 mx-auto flex md:items-center lg:items-start md:flex-row md:flex-nowrap flex-wrap flex-col">
            <div class="w-64 flex-shrink-0 md:mx-0 mx-auto text-center md:text-left">
                <a class="flex title-font font-medium items-center text-white mb-4 md:mb-0">
                    <img src="https://s3.amazonaws.com/designmantic-logos/logos/2021/Mar/small-5145-605b76628a895.png" alt>
                    <span class="ml-3 text-xl">पाठशाला</span>
                </a>
                <p class="mt-2 text-sm text-gray-500">Leadership and learning are indispensable to each other.</p>
            </div>

                    {% if user.is_authenticated %}
                    <nav class="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center">
                        <a class="mr-8 hover:text-white" href="{% url 'index' %}">E-Learning</a>
                        <a class="mr-8 hover:text-white" href="{% url 'learn:courselist' %}">Courses</a>
                        <a class="mr-8 hover:text-white" href="{% url 'learn:contact' %}">Contact</a>
                        <a class="mr-8 hover:text-white" href="{% url 'learn:curriculum' %}">Curriculum</a>
                        <a class="mr-8 hover:text-white" href="{% url 'about' %}">About</a>
                        <a class="mr-8 hover:text-white" href="{% url 'learn:cartlist' %}">Cart</a>
                    </nav>
                    {% else %}
                    <nav class="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center">
                        <a class="mr-8 hover:text-white" href="{% url 'index' %}">E-Learning</a>
                        <a class="mr-8 hover:text-white" href="{% url 'learn:courselist' %}">Courses</a>
                        <a class="mr-8 hover:text-white" href="{% url 'learn:contact' %}">Contact</a>
                        <a class="mr-8 hover:text-white" href="{% url 'about' %}">About</a>
                    </nav>
                    {% endif %}

        </div>

        <div class="bg-pink-800 bg-opacity-75">
            <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
                <p class="text-gray-400 text-sm text-center sm:text-left">
                    &#169 2021
                    <a href="https://github.com/Pawanpoudel-del" rel="noopener noreferrer" class="text-gray-500 ml-1" target="_blank">@पाठशाला</a>
                </p>
                <span class="inline-flex sm:ml-auto sm:mt-0 mt-2 justify-center sm:justify-start">
                    <a class="text-gray-400" href="https://www.facebook.com/profile.php?id=100010615395943">
                        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                            <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                        </svg>
                    </a>
                    <a class="ml-3 text-gray-400" href="https://twitter.com/PawanPo18651862">
                        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                            <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
                        </svg>
                    </a>
                    <a class="ml-3 text-gray-400" href="https://www.instagram.com/pawan__poudel/">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                            <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
                            <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
                        </svg>
                    </a>
                </span>
            </div>
        </div>
    </footer>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %} | E-Learning {% endblock %}
{% block bodyblock %}


<section class="text-gray-400 bg-blue-900 body-font">
    <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
        <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 md:mb-0 mb-10">
            <img class="object-cover object-center rounded" alt="hero" src="https://railbeeps.com/images/stations/PBL.png?20170803-1">
        </div>
        <div class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
            <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-white">
                कहिलेकाही अज्ञानी भनिएकाबाट पनि शिक्षा मिल्छ ।
                <br class="hidden lg:inline-block">शिक्षा नै धर्म हो ।
            </h1>
            <p class="mb-8 leading-relaxed">E-learning could be a structured course or learning experience delivered electronically; it may include performance support content. While ATD style uses a hyphen within the spelling, you'll also see it spelled elearning or eLearning.</p>
            <div class="flex justify-center">
                <a href="{% url 'about' %}"><button class="inline-flex text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded text-lg">About</button></a>
                <a href="{% url 'learn:contact' %}"> <button class="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg" >Contact</button></a>
            </div>
        </div>
    </div>
</section>

<section class="text-gray-400 bg-blue-900 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-wrap -m-4">
            <div class="lg:w-1/3 lg:mb-0 mb-6 p-4">
                <div class="h-full text-center">
                    <img alt="testimonial" class="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-800 bg-gray-800 bg-opacity-10" src="https://files.softicons.com/download/web-icons/user-icons-by-mike-demetriou/png/256/user%20green.png" >
                    <p class="leading-relaxed">Complete backend developer</p>
                    <span class="inline-block h-1 w-10 rounded bg-red-500 mt-6 mb-4"></span>
                    <h2 class="text-white font-medium title-font tracking-wider text-sm">Pawan Poudel</h2>
                    <p class="text-gray-500">Backend Developer</p>
                </div>
            </div>
            <div class="lg:w-1/3 lg:mb-0 mb-6 p-4">
                <div class="h-full text-center">
                    <img alt="testimonial" class="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-800 bg-gray-800 bg-opacity-10" src="https://icon-library.com/images/little-person-icon/little-person-icon-19.jpg" >
                    <p class="leading-relaxed">Complete UI developer</p>
                    <span class="inline-block h-1 w-10 rounded bg-red-500 mt-6 mb-4"></span>
                    <h2 class="text-white font-medium title-font tracking-wider text-sm">Sulav Homagai</h2>
                    <p class="text-gray-500">UI Develeoper</p>
                </div>
            </div>
            <div class="lg:w-1/3 lg:mb-0 p-4">
                <div class="h-full text-center">
                    <img alt="testimonial" class="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-800 bg-gray-800 bg-opacity-10" src="https://cdn.pixabay.com/photo/2014/04/02/10/52/person-304798_640.png" >
                    <p class="leading-relaxed">Testings are done by Nishan</p>
                    <span class="inline-block h-1 w-10 rounded bg-red-500 mt-6 mb-4"></span>
                    <h2 class="text-white font-medium title-font tracking-wider text-sm">Nishan Timsina</h2>
                    <p class="text-gray-500">Testings</p>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}